:numbered:
:toc:
= Obvious Path of Progression

== Scenarios
* The *Scenario* tab in the Insert Tool probably requires an 'accordian' listing.
There may be an opportunity to condense all objects,styles and scenarios into one list.

* Adding a 'Scenario Builder' to the *Scenario* tab in the Insert Tool. 

* Research into automating layout creation for data / database queries.

== Validators
* The work for validators has been started in the setup-style environment.
Further customization options need to be looked at.

== Requesters
* Good Requesters for: colour, rich-text, pair and others need to be built.
* A general purpose request-input requester could be made from the *setup-style* requester pattern.


== Red Storage Framework
* Longer term project to deal with sub 10,000 record database use cases.

== Direct Code test-bench
* Build a useable version of the `test-bench` program used for internal Direct Code development.

== Direct Code dev-print
* Build a useable version of the `dprint` function used for internal Direct Code development.